import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import NextTopLoader from "nextjs-toploader";

// ----------------- import UI
import { Background } from "@/ui/background/Background";
import { Header } from "@/ui/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Seovileo",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    title,
}: {
    children: React.ReactNode;
    title: string;
}) {
    return (
        <html lang="pl">
            <body className={`min-h-screen w-full ${inter.className}`}>
                <NextTopLoader
                    color="#36a5e6"
                    initialPosition={0.08}
                    crawlSpeed={200}
                    height={2.7}
                    crawl={true}
                    showSpinner={false}
                    easing="ease"
                    speed={200}
                    shadow="0 0 25px #3caff1,0 0 15px #2299DD"
                    zIndex={1600}
                    showAtBottom={false}
                />
                <Header />
                {/* <Background /> */}
                <main className="max-w-screen-2xl mx-auto">{children}</main>
                <div className="h-[200vh]" />
            </body>
        </html>
    );
}
