import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import NextTopLoader from "nextjs-toploader";

// ----------------- import UI
import { Background } from "@/ui/background/Background";
import { Header } from "@/ui/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Seovileo",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    title,
}: {
    children: React.ReactNode;
    title: string;
}) {
    return (
        <html lang="pl">
            <body className={`min-h-screen w-full overflow-x-hidden ${inter.className}`}>
                {/* <NextTopLoader
                    color="#a40220"
                    initialPosition={0.08}
                    crawlSpeed={200}
                    height={2.7}
                    crawl={true}
                    showSpinner={false}
                    easing="ease"
                    speed={200}
                    zIndex={1600}
                    showAtBottom={false}
                /> */}
                <Header />
                <main className="max-w-screen-[2000px] mx-auto text-gray-200 lg:px-5">
                    {children}
                </main>
                <Background />
                <div className="h-[200vh]" />
            </body>
        </html>
    );
}
