import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";

// ----------------- import UI
import { Background } from "@/ui/background/Background";
import { Header } from "@/ui/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Fotograf",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="pl">
            <body className={inter.className}>
                <Header />
                <main className="max-w-screen-[2000px] mx-auto text-gray-200 lg:px-5">
                    {children}
                </main>
                <Background />
            </body>
        </html>
    );
}
